# authentication error messages
authentication.err.validation.authenticator.notfound=Der kunne ikke godkendes. Godkenderen {0} blev ikke fundet
authentication.err.validation.authenticator.notactive=Godkenderen er ikke aktiv

authentication.err.authentication=Der kunne ikke godkendes. Brugernavnet eller adgangskoden er forkert. Brugernavn: {0} \u00c5rsag: {1}
authentication.err.connection=Der kunne ikke oprettes forbindelse til {0}. \u00c5rsag: {1}
authentication.err.communication=Der kunne ikke kommunikeres med {0}. \u00c5rsag: {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Der kunne ikke oprettes forbindelse. LDAP-v\u00e6rten {0} er ukendt
authentication.err.connection.ldap.user.notfound=LDAP-brugeren {0} blev ikke fundet
authentication.err.connection.ldap.manager.notfound=LDAP-administratorbrugeren {0} blev ikke fundet
authentication.err.connection.ldap.search=Der kunne ikke s\u00f8ges i LDAP. \u00c5rsag: {0}

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Validering af anmodning
authentication.step.ldap.connecting=Opretter forbindelse til LDAP-serveren {0}
authentication.step.ldap.connected=Der blev oprettet forbindelse til LDAP-serveren {0} med sikkerhedskontoen: {1}
authentication.step.ldap.lookup=Sl\u00e5 testbrugeren med userId {0} op med foresp\u00f8rgslen {1}
authentication.step.ldap.lookedup=Testbrugeren med userId {0} blev sl\u00e5et op. Der blev fundet f\u00f8lgende entydige navn: {1}
authentication.step.ldap.format.user=Formatet af brugernavnet er angivet, userNameFormat:{2} Format\u00e9r brugers userId:{0} for at oprette entydigt navn:{1}
authentication.step.ldap.authentication=Godkend userId:{0}


# Sync Summary message 
synchronization.summary.status={0} bruger(e) og {1} gruppe(r) blev behandlet


# Error messages
authentication.ldap.validation.authenticator.notfound=Godkenderen blev ikke fundet

# Synchronization Diagnostic Steps
synchronization.step.users=Der blev fundet {0} brugere
synchronization.step.groups=Der blev fundet {0} grupper
synchronization.step.users.lastsynced=Brugerne blev senest synkroniseret {0}
synchronization.step.groups.lastsynced=Grupperne blev senest synkroniseret {0}

synchronization.err.ldap.search=Der opstod fejl under LDAP-s\u00f8gning. \u00c5rsag:{0}
synchronization.err.ldap.get.user.id.missing=Brugeren mangler bruger-id-attributten DN (entydigt navn) = {0}, attributeName = {1})
synchronization.err.ldap.get.group.id.missing=Gruppen mangler gruppe-id-attributten DN (entydigt navn) = {0}, attributeName = {1})

synchronization.err.ldap.search.base.invalid=Ugyldig s\u00f8gebasis {0}. \u00c5rsag: {1}

synchronization.err.ldap.group.member.missing.exception="Medlemmet af gruppen {0} blev ikke fortolket med det entydige navn: {1}. \u00c5rsag: {2});
synchronization.err.ldap.group.member.missing="Medlemmet af gruppen {0} blev ikke fortolket med det entydige navn: {1});







